name: Pulsar Build

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Install linters
      run:  go install golang.org/x/lint/golint@latest

    - name: Linting
      run:  golint -set_exit_status ./...

    - name: Run Tests
      run:  go test ./...

    - name: Build Pulsar
      run:  go build -v -ldflags '-s -w'