name: Pulsar Build

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install linters
        run: go install golang.org/x/lint/golint@latest

      - name: Linting
        run: golint ./...

      - name: Build Pulsar
        run: go build -v -ldflags '-s -w'