name: Schema Verification

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Verify Database Schema
      uses: yokawasa/action-sqlcheck@v1.4.0
      with:
        post-comment: true
        risk-level: 3
        verbose: true
        token: ${{ secrets.GITHUB_TOKEN }}
        postfixes: |
          sql
        directories: |
          extra/schema
